# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# ----------------------------
# Layout: インデントと空白行のルール
# ----------------------------

Layout/IndentationWidth:
  Width: 2

Layout/EmptyLinesAroundMethodBody:
  Enabled: true

Layout/EmptyLinesAroundClassBody:
  Enabled: true

Layout/EmptyLineBetweenDefs:
  Enabled: true

Layout/EmptyLines:
  Max: 1
